import type { Metadata } from "next";
import "./globals.css";
import { Nav } from "@/components/Nav/nav";

import { Raleway } from 'next/font/google';
import NextTopLoader from 'nextjs-toploader';

const raleway = Raleway({ subsets: ['latin'], weight: ['400', '700'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Foso Soft</title>
      </head>
      <body className={raleway.className}>
        <NextTopLoader color="#76E6C1" height={10} showSpinner={false} />
        <Nav />
        {children}
      </body>
    </html>
  );
}
